Feature pagination and post functionalities
tejasvikolhe01/social-media-app pull request #5
Opened 2024-07-09 09:01 UTC by tejasvikolhe01

Hi Team,

1. Added pagination
2. Sorted post by created date.

Thank you

2024-07-09 13:49 UTC, MattX23 requested changes
The pagination looks to be working well.

One thing though - I would clear the input after the comment has been submitted:

![Screenshot 2024-07-09 at 14 48 26](https://github.com/tejasvikolhe01/social-media-app/assets/44146390/d84d86fe-3bb2-4ace-abf3-5cb22c9e33f2)

2024-07-10 07:26 UTC, alex-bowers commented on resources/js/Pages/Dashboard.vue
> +                            <a  href="javascript:void(0)" @click="loadMorePosts(link.url)">{{ index }}</a>
Why do you need `javascript:void(0)`?

2024-07-10 07:28 UTC, alex-bowers commented on resources/js/Pages/Dashboard.vue
> +                                    <a v-bind:class="{ active: link.active }" class="page-link" @click="loadMorePosts(link.url)" v-if="index>0 && index<loadMoreLinks.length-1" href="javascript:void(0
You don't need to type `v-bind` in this instance. Just typing `:class` works the same way.

2024-07-10 07:29 UTC, alex-bowers commented on resources/js/Pages/Dashboard.vue
> +                    this.loadMoreLinks = response.data.links;
Can you destruct `response.data`?

2024-07-11 15:13 UTC, MattX23 approved these changes

2024-07-11 15:41 UTC, alex-bowers approved these changes

2024-07-11 16:43 UTC, merged